exerhealth/accounts/urls.py
from django.urls import path
from exerhealth.accounts import views

app_name = 'accounts'

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_page, name='logout'),
    path('profile/', views.profile_page, name='profile'),
    path('profile/bmi_calculator/', views.bmi_calculator, name='bmi_calculator'),
    path('profile/bmi_calculator/bmi_plot', views.bmi_plot, name='bmi_plot'),

]

exerhealth/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin', admin.site.urls),
    path('', include('exerhealth.accounts.urls', )),
    path('clothing-store/', include('exerhealth.clothingstore.urls', namespace='clothes')),
    path('basket/', include('exerhealth.store_basket.urls')),
    path('order/', include('exerhealth.orders.urls')),
    path('forum/', include('exerhealth.forum.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('calorie-tracker/', include('exerhealth.calorie_tracker.urls'))
]

templates/profile/bmi.html
<p>Your BMI is: {{ bmi }}</p>
<p>You are {{ status }}</p>
<img src="data:image/png;base64, {{ plot|safe }}" alt="BMI Plot">

templates/profile/profile.html
{% extends 'index.html' %}
{% block title %}Профил{% endblock title %}
{% block url_title %}Profile{% endblock url_title %}
{% block content %}
    <p>Age: {{ fitness_profile.age }}</p>
    <p>Weight: {{ fitness_profile.weight }}</p>
    <p>Height: {{ fitness_profile.height }}</p>
    <p>Goal: {{ fitness_profile.goal }}</p>
    <p>Bio: {{ fitness_profile.bio }}</p>
    <form action="{% url 'accounts:bmi_calculator' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Calculate BMI">
</form>
{% endblock content %}