exerhealth/accounts/urls.py
from django.urls import path
from exerhealth.accounts import views

app_name = 'accounts'

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_page, name='logout'),
    path('profile/', views.profile_page, name='profile'),
    path('profile/bmi_calculator/', views.bmi_calculator, name='bmi_calculator'),
    path('profile/bmi_calculator/bmi_plot', views.bmi_plot, name='bmi_plot'),

]

exerhealth/clothingstore/urls.py
from django.urls import path
from exerhealth.clothingstore import views

app_name = 'clothingstore'

urlpatterns = [
    path('', views.product_all, name='product_all'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('<slug:category_slug>', views.category_list, name='category_list'),
]

exerhealth/forum/urls.py
from django.urls import path
from exerhealth.forum import views

app_name = 'forum'

urlpatterns = [
    path('category/<int:category_id>/<int:page_number>/', views.thread_list, name='thread_list'),
    path('thread/<int:thread_id>/<int:page_number>/', views.thread_detail, name='thread_detail'),
    path('new_thread/<int:category_id>/', views.new_thread, name='new_thread'),
    path('reply_thread/<int:thread_id>/', views.reply_thread, name='reply_thread'),
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
    # path('search/', views.search, name='search'),
]

exerhealth/store_basket/urls.py
from django.urls import path
from . import views

app_name = 'store_basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('update/', views.basket_update, name='basket_update'),
    path('delete/', views.basket_delete, name='basket_delete'),
]

exerhealth/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin', admin.site.urls),
    path('', include('exerhealth.accounts.urls', )),
    path('clothing-store/', include('exerhealth.clothingstore.urls', namespace='clothes')),
    path('basket/', include('exerhealth.store_basket.urls')),
    path('order/', include('exerhealth.orders.urls')),
    path('forum/', include('exerhealth.forum.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('calorie-tracker/', include('exerhealth.calorie_tracker.urls'))
]

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.6.1.min.js"></script>

    <title>ExerHealth - {% block url_title %}{% endblock url_title %}</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="/static/assets/img/favicon.png" rel="icon">
    <link href="/static/assets/img/icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="/static/assets/vendor/animate.css/animate.min.css" rel="stylesheet">
    <link href="/static/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="/static/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="/static/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="/static/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="/static/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="/static/assets/css/style.css" rel="stylesheet">
</head>

<body>

<!-- ======= Header ======= -->
<header id="header" class="fixed-top header-inner-pages">
    <div class="container d-flex align-items-center justify-content-between">
        <h1 class="logo"><a href="/">ExerHealth</a></h1>
        <nav id="navbar" class="navbar">
            <ul>
                <li><a class="nav-link scrollto" href="/foodsupplies">Хранителни добавки</a></li>
                <li class="dropdown"><a href="{% url 'clothingstore:product_all' %}"><span>Облекло и аксесоари</span><i
                        class="bi bi-chevron-down"></i></a>
                    <ul>
                        <li><a href="">Блузи</a></li>
                        <li><a href="">Екипи</a></li>
                        <li><a href="">Обувки</a></li>
                        <li><a href="">Долнища</a></li>
                        <li><a href="">Бельо</a></li>
                    </ul>
                </li>
                <li><a class="nav-link scrollto" href="/fitnessgoals">Фитнес цели</a></li>
                <li><a class="nav-link  scrollto" href="{% url 'forum:thread_list' 1 1 %}">Форум</a></li>
                {% if user.is_authenticated %}
                    <li class="dropdown">
                    <a href="{% url 'accounts:profile' %}"><span>Профил</span> <i class="bi bi-chevron-down"></i></a>
                    <ul>
                        <li><a href="{% url 'calorie_tracker:show_food_lists' %}">Drop Down 1</a></li>
                        <li><a href="#">Drop Down 2</a></li>
                        <li><a href="#">Drop Down 3</a></li>
                        <li><a href="#">Drop Down 4</a></li>
                    </ul>
                {% endif %}
                {% if user.is_authenticated %}
                    <li><a class="nav-link scrollto" href="{% url 'store_basket:basket_summary' %}">Кошница -
                        {% with total_qty=basket|length %}
                            <div id="basket-qty" class="d-inline-flex">
                                {% if total_qty > 0 %}
                                    {{ total_qty }}
                                {% else %}
                                    0
                                {% endif %}
                            </div>
                        {% endwith %}
                    </a>
                    </li>
                {% endif %}
                {% if request.user.is_authenticated %}
                    <li class="main_button"><a href="{% url 'accounts:logout' %}">Изход</a></li>
                {% else %}
                    <li class="main_button"><a href="{% url 'accounts:signup' %}">Регистрация</a></li>
                {% endif %}
            </ul>
            <i class="bi bi-list mobile-nav-toggle"></i>
        </nav>
    </div>
</header><!-- End Header -->

<!-- ======= Hero Section ======= -->
<section id="hero">
    <div id="heroCarousel" data-bs-interval="5000" class="carousel slide carousel-fade" data-bs-ride="carousel">
        <div class="carousel-inner" role="listbox">
            <div class="carousel-item active"
                 style="background-image: {% block image %}url(/static/assets/img/slide/logo-slide.jpg){% endblock image %}">
                <div class="carousel-container">
                    <div class="container">
                        <h2 class="animated fadeInDown">{% block title %}Добре дошли в
                            ExerHealth{% endblock title %}</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section><!-- End Hero -->

<main id="main">{% block content %}{% endblock content %}</main>

<!-- ======= Footer ======= -->
<footer id="footer">
    <div class="footer-top">
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-xl-10">
                    <div class="row">
                        <div class="col-lg-3 col-md-6 footer-links">
                            <h4>Полезно</h4>
                            <ul>
                                <li><i class="bx bx-chevron-right"></i> <a href="#">Помощ за клиенти</a></li>
                                <li><i class="bx bx-chevron-right"></i> <a href="#">Услуги</a></li>
                                <li><i class="bx bx-chevron-right"></i> <a href="#">Доставка</a></li>
                            </ul>
                        </div>
                        <div class="col-lg-3 col-md-6 footer-links">
                            <h4>Информация</h4>
                            <ul>
                                <li><i class="bx bx-chevron-right"></i> <a href="#">Политика за поверителност</a></li>
                                <li><i class="bx bx-chevron-right"></i> <a href="#">Политика за "Бисквитки"</a></li>
                                <li><i class="bx bx-chevron-right"></i> <a href="#">Връщане и замяна</a></li>
                                <li><i class="bx bx-chevron-right"></i> <a href="#">Общи Условия</a></li>
                            </ul>
                        </div>
                        <div class="col-lg-3 col-md-6 footer-contact">
                            <h4>Свържете се с нас</h4>
                            <p>
                                ул. Атанас Манчев <br>
                                София, Студентски град<br>
                                България <br><br>
                                <strong>Телефон:</strong> +359 878 123 456<br>
                                <strong>Имейл:</strong> exerhealth@example.com<br>
                            </p>
                        </div>
                        <div class="col-lg-3 col-md-6 footer-info">
                            <h3>За нас</h3>
                            <p>Фитнес платформа, покриваща <br>
                                всички нужди.</p>
                            <div class="social-links mt-3">
                                <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                                <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                                <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                                <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                                <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer><!-- End Footer -->

<div id="preloader"></div>
<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
        class="bi bi-arrow-up-short"></i></a>

<!-- Vendor JS Files -->
<script src="/static/assets/vendor/purecounter/purecounter_vanilla.js"></script>
<script src="/static/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="/static/assets/vendor/glightbox/js/glightbox.min.js"></script>
<script src="/static/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
<script src="/static/assets/vendor/swiper/swiper-bundle.min.js"></script>
<script src="/static/assets/vendor/waypoints/noframework.waypoints.js"></script>
<script src="/static/assets/vendor/php-email-form/validate.js"></script>

<!-- Template Main JS File -->
<script src="/static/assets/js/main.js"></script>

</body>

</html>