exerhealth/store_basket/urls.py
from django.urls import path
from . import views

app_name = 'store_basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('update/', views.basket_update, name='basket_update'),
    path('delete/', views.basket_delete, name='basket_delete'),
]

exerhealth/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin', admin.site.urls),
    path('', include('exerhealth.accounts.urls', )),
    path('clothing-store/', include('exerhealth.clothingstore.urls', namespace='clothes')),
    path('basket/', include('exerhealth.store_basket.urls')),
    path('order/', include('exerhealth.orders.urls')),
    path('forum/', include('exerhealth.forum.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('calorie-tracker/', include('exerhealth.calorie_tracker.urls'))
]

exerhealth/store_basket/models.py
from django.db import models

# Create your models here.

exerhealth/store_basket/views.py
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from exerhealth.clothingstore.models import Product
from .basket import StoreBasket


@login_required(login_url=login)
def basket_summary(request):
    basket = StoreBasket(request)
    context = {'basket': basket}
    return render(request, 'basket/store_basket.html', context)


@login_required(login_url=login)
def basket_add(request):
    basket = StoreBasket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        product = get_object_or_404(Product, id=product_id)
        basket.add(product=product, qty=product_qty)

        basket_qty = basket.__len__()
        response = JsonResponse({'qty': basket_qty})
        return response


@login_required(login_url=login)
def basket_update(request):
    basket = StoreBasket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        basket.update(product=product_id, qty=product_qty)
        basket_qty = basket.__len__()
        basket_total = basket.get_total_price()
        response = JsonResponse({'qty': basket_qty, 'subtotal': basket_total})
        return response


@login_required(login_url=login)
def basket_delete(request):
    basket = StoreBasket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        basket.delete(product=product_id)
        basket_qty = basket.__len__()
        basket_total = basket.get_total_price()
        response = JsonResponse({'qty': basket_qty, 'subtotal': basket_total})
        return response

templates/basket/store_basket.html
{% extends 'index.html' %}
{% block title %}Количка{% endblock title %}
{% block url_title %}Basket{% endblock url_title %}
{% block content %}
    <main class="pt-5">
        <div class="container">
            <h1 class="h1">Количка</h1>
            {% for item in basket %}
                {% with product=item.product %}
                    <div data-index="{{ product.id }}" class="row mb-4 border product-item">
                        <div class="col-md-3 col-lg-2 order-md-first bg-light">
                            <img class="img-fluid mx-auto d-block" width="200px" height="200px" alt="Responsive image"
                                 src="{{ product.image.url }}">
                        </div>
                        <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10">
                            <a href="{{ product.get_absolute_url }}" class="text-decoration-none text-reset">
                                <h1 class="h5 pt-2">{{ product.title }}</h1>
                            </a>
                            <div class="border">
                                <div class="col border-bottom">
                                    <div class="row p-3">
                                        <div class="col-6">Цена:</div>
                                        <div class="col-6 text-end"><span
                                                class="h6 fw-bold">{{ product.price }}лв.</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="row p-3">
                                        <div class="col-12">
                                            <label for="select">Количество:</label>
                                            <select id="select{{ product.id }}">
                                                <option selected>
                                                    {{ item.qty }}
                                                </option>
                                                <option value="">1</option>
                                                <option value="">2</option>
                                                <option value="">3</option>
                                                <option value="">4</option>
                                            </select>
                                            <button type="button" id="update-button" data-index="{{ product.id }}"
                                                    class="btn btn-outline-secondary btn-sm update-button">
                                                Aктуализация
                                            </button>
                                            <button type="button" id="delete-button" data-index="{{ product.id }}"
                                                    class="btn btn-outline-secondary btn-sm delete-button">
                                                Изтриване
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endwith %}
            {% endfor %}
            <div class="col-12 text-end">
                <div class="h6 fw-bold">Обща цена:
                    <div id="subtotal" class="d-inline-flex">{{ basket.get_total_price }}лв.</div>
                </div>
            </div>
            <div class="col-12 text-end">
                <div class="h4 fw-bold">
                    <div id="paypal-button-container">
                    </div>
                </div>
            </div>
        </div>
    </main>

    <script>
        $(document).on('click', '.update-button', function (e) {
            e.preventDefault();
            var prodid = $(this).data('index');
            $.ajax({
                type: 'POST',
                url: '{% url 'store_basket:basket_update' %}',
                data: {
                    productid: $(this).data('index'),
                    productqty: $('#select' + prodid + ' option:selected').text(),
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                    action: 'post'
                },
                success: function (json) {
                    document.getElementById('basket-qty').innerHTML = json.qty
                    document.getElementById('subtotal').innerHTML = json.subtotal
                },
                error: function (xhr, errmsg, err) {
                }
            });
        })


        $(document).on('click', '.delete-button', function (e) {
            e.preventDefault();
            var prodid = $(this).data('index');
            $.ajax({
                type: 'POST',
                url: '{% url 'store_basket:basket_delete' %}',
                data: {
                    productid: $(this).data('index'),
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                    action: 'post'
                },
                success: function (json) {
                    $('.product-item[data-index="' + prodid + '"]').remove();
                    document.getElementById('subtotal').innerHTML = json.subtotal;
                    document.getElementById('basket-qty').innerHTML = json.qty
                },
                error: function (xhr, errmsg, err) {
                }
            });
        })

    </script>


    <script src="https://www.paypal.com/sdk/js?client-id=AZuvPDOLHEnaauqKVhav2jivF4Pkwh2bCr-1EieXWTXZGFIo1G2Tf2k6ESyBQX4SOxNsGVd5zIoUFCoh&currency=USD"></script>

    <script>
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({

            // Set up the transaction
            createOrder: function (data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: '{{ basket.get_total_price }}'
                        }
                    }]
                });
            },

            // Finalize the transaction
            onApprove: function (data, actions) {
                return actions.order.capture().then(function (orderData) {
                    // Successful capture! For demo purposes:
                    console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
                    var transaction = orderData.purchase_units[0].payments.captures[0];
                    alert('Transaction ' + transaction.status + ': ' + transaction.id + '\n\nSee console for all available details');


                    // Replace the above to show a success message within this page, e.g.
                     {#const element = document.getElementById('paypal-button-container');#}
                     {#element.innerHTML = '';#}
                     {#element.innerHTML = '<h3>Thank you for your payment!</h3>';#}
                    // Or go to another URL:
                     //actions.redirect('thank_you.html');
                });
            }
        }).render('#paypal-button-container');
    </script>
{% endblock content %}