exerhealth/forum/urls.py
from django.urls import path
from exerhealth.forum import views

app_name = 'forum'

urlpatterns = [
    path('category/<int:category_id>/<int:page_number>/', views.thread_list, name='thread_list'),
    path('thread/<int:thread_id>/<int:page_number>/', views.thread_detail, name='thread_detail'),
    path('new_thread/<int:category_id>/', views.new_thread, name='new_thread'),
    path('reply_thread/<int:thread_id>/', views.reply_thread, name='reply_thread'),
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
    # path('search/', views.search, name='search'),
]

exerhealth/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin', admin.site.urls),
    path('', include('exerhealth.accounts.urls', )),
    path('clothing-store/', include('exerhealth.clothingstore.urls', namespace='clothes')),
    path('basket/', include('exerhealth.store_basket.urls')),
    path('order/', include('exerhealth.orders.urls')),
    path('forum/', include('exerhealth.forum.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('calorie-tracker/', include('exerhealth.calorie_tracker.urls'))
]

exerhealth/forum/models.py
from django.db import models
from django.contrib.auth.models import User
from mptt.models import MPTTModel, TreeForeignKey
from notifications.models import Notification


class Category(MPTTModel):
    name = models.CharField(max_length=255)
    description = models.TextField()
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class MPTTMeta:
        verbose_name_plural = 'Categories'
        order_insertion_by = ['name']

    def __str__(self):
        return self.name


class Thread(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='created_thread')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    views = models.IntegerField(default=0)
    solved = models.BooleanField(default=False)
    sticky = models.BooleanField(default=False)
    closed = models.BooleanField(default=False)
    last_post_date = models.DateTimeField(auto_now=True)
    last_post_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='related_post_thread')

    def __str__(self):
        return self.title


class Post(models.Model):
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='created_post')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    body = models.TextField()
    edited = models.BooleanField(default=False)
    edited_at = models.DateTimeField(auto_now=True)
    edited_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='edited_post')

    def __str__(self):
        return self.body[:50] + '...'


class ForumNotification(Notification):
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE, related_name='thread_notify')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post_notify')

    class Meta:
        index_together = [
            ["thread", "post"],
        ]

exerhealth/forum/views.py
from django.utils import timezone
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required, permission_required
from django.core.paginator import Paginator
from .models import Category, Thread, Post
from django.contrib.auth.models import User
from notifications.signals import notify

app_name = 'forum'


def thread_list(request, category_id, page_number):
    category = get_object_or_404(Category, id=category_id)
    threads = Thread.objects.filter(category=category).order_by('-sticky', '-last_post_date')
    paginator = Paginator(threads, 10)
    page_obj = paginator.get_page(page_number)
    context = {'category': category, 'page_obj': page_obj}
    return render(request, 'forum/thread_list.html', context)


def thread_detail(request, thread_id, page_number):
    thread = get_object_or_404(Thread, id=thread_id)
    thread.views += 1
    thread.save()
    posts = thread.post_set.all().order_by('created_at')
    paginator = Paginator(posts, 10)
    page_obj = paginator.get_page(page_number)
    context = {'thread': thread, 'page_obj': page_obj}
    return render(request, 'forum/thread_detail.html', context)


@login_required
def new_thread(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    if request.method == 'POST':
        thread = Thread.objects.create(
            category=category,
            title=request.POST['title'],
            created_by=request.user
        )
        post = Post.objects.create(
            thread=thread,
            created_by=request.user,
            body=request.POST['body']
        )
        recipient_user = User.objects.filter(is_superuser=True)
        notify.send(request.user, recipient=recipient_user, verb='created a new thread', target=thread,
                    action_object=post)
        return redirect('thread_detail', thread_id=thread.id, page_number=1)
    else:
        context = {'category': category}
    return render(request, 'forum/new_thread.html', context)


@login_required
@permission_required('forum.add_post', raise_exception=True)
def reply_thread(request, thread_id):
    thread = get_object_or_404(Thread, id=thread_id)
    if request.method == 'POST':
        post = Post.objects.create(
            thread=thread,
            created_by=request.user,
            body=request.POST['body']
        )
        thread.last_post_date = post.created_at
        thread.last_post_by = request.user
        thread.save()
        notify.send(request.user, recipient=thread.created_by, verb='replied to your thread', target=thread,
                    action_object=post)
        return redirect('thread_detail', thread_id=thread.id, page_number=1)
    else:
        context = {'thread': thread}
    return render(request, 'forum/reply_thread.html', context)


@login_required
@permission_required('forum.add_post', raise_exception=True)
def edit_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == 'POST':
        post.body = request.POST['body']
        post.edited = True
        post.edited_at = timezone.now()
        post.edited_by = request.user
        post.save()
        return redirect('thread_detail', thread_id=post.thread.id, page_number=1)
    else:
        context = {'post': post}
    return render(request, 'forum/edit_post.html', context)

templates/forum/edit_post.html
{% extends 'index.html' %}
{% block url_title %}Форум-{{ category.name }}{% endblock url_title %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <label for="body">Body:</label>
    <textarea id="body" name="body" required>{{ post.body }}</textarea>
    <br>
    <input type="submit" value="Save changes">
</form>
{% endblock content %}

templates/forum/new_thread.html
{% extends 'index.html' %}
{% block url_title %}Форум-{{ category.name }}{% endblock url_title %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <label for="title">Title:</label>
    <input type="text" id="title" name="title" required>
    <br>
    <label for="body">Body:</label>
    <textarea id="body" name="body" required></textarea>
    <br>
    <input type="submit" value="Create thread">

</form>
{% endblock content %}

templates/forum/reply_thread.html
{% extends 'index.html' %}
{% block url_title %}Форум-{{ category.name }}{% endblock url_title %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <label for="body">Body:</label>
    <textarea id="body" name="body" required></textarea>
    <br>
    <input type="submit" value="Reply">
</form>
{% endblock content %}

templates/forum/thread_detail.html
{% extends 'index.html' %}
{% block title %}<h2>{{ thread.title }}</h2>{% endblock title %}
{% block url_title %}Форум-{{ category.name }}{% endblock url_title %}
{% block content %}
<ul>
{% for post in page_obj %}
    <li>{{ post.body }}</li>
{% endfor %}
</ul>
<div>
    {% if page_obj.has_previous %}
        <a href="{% url 'forum:thread_detail' thread.id page_number=page_obj.previous_page_number %}">Previous</a>
    {% endif %}
    {% if page_obj.has_next %}
        <a href="{% url 'forum:thread_detail' thread.id page_number=page_obj.next_page_number %}">Next</a>
    {% endif %}
</div>
<div>
    <a href="{% url 'forum:reply_thread' thread.id %}">Reply</a>
</div>
{% endblock content %}

templates/forum/thread_list.html
{% extends 'index.html' %}
{% block title %}<h2>{{ category.name }}</h2>{% endblock title %}
{% block url_title %}Форум-{{ category.name }}{% endblock url_title %}
{% block content %}
<ul>
{% for thread in page_obj %}
    <li><a href="{% url 'forum:thread_detail' 1 1 %}">{{ thread.title }}</a></li>
{% endfor %}
</ul>
<div>
    {% if page_obj.has_previous %}
        <a href="{% url 'forum:thread_list' category.id page_number=page_obj.previous_page_number %}">Previous</a>
    {% endif %}
    {% if page_obj.has_next %}
        <a href="{% url 'forum:thread_list' category.id page_number=page_obj.next_page_number %}">Next</a>
    {% endif %}
</div>
{% endblock content %}